### ISSUE TITLE
Make the Cinemachine free look work only on mouse drag

### ISSUE THREAD

**Issue by gavrilovmiroslav** [3dnd/3dnd.battlemat#10]
The original free look moves with the mouse cursor, but we need it to work on mouse drag. Hints on how to do this could be found [here](https://forum.unity.com/threads/can-the-freelook-cameras-motion-be-limited-by-additional-keys.507799/).

**Comment by gavrilovmiroslav** [comment]
The `Campaign` scene has a mock camera that this will be tested on, in the `Observer` object.

**Comment by rastko1996** [comment]
Add **ModifyCamera** component to CinemachineCamera and assign desired modifier to it. In this case, **FreeLookDragOnly**.
